version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: ["uvicorn", "nl2sql.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      NL2SQL_REDIS_URL: redis://redis:6379/0
      NL2SQL_DATABASE_URL: sqlite+aiosqlite:///./data/metadata.db
      NL2SQL_OBJECT_STORE_PATH: /app/data/artifacts
      NL2SQL_CORS_ORIGINS: http://localhost:5173
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
      - nl2sql-data:/app/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: ["arq", "nl2sql.jobs.worker.WorkerSettings"]
    environment:
      NL2SQL_REDIS_URL: redis://redis:6379/0
      NL2SQL_DATABASE_URL: sqlite+aiosqlite:///./data/metadata.db
      NL2SQL_OBJECT_STORE_PATH: /app/data/artifacts
    depends_on:
      - redis
    volumes:
      - .:/app
      - nl2sql-data:/app/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      VITE_API_BASE: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./web:/web

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  nl2sql-data:
